;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Effects.HitReaction",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.AnimClass",DevComment="")
+GameplayTagList=(Tag="Event.Combo.End",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Input",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Start",DevComment="")
+GameplayTagList=(Tag="Event.Dash",DevComment="")
+GameplayTagList=(Tag="Event.FOV.Decrease",DevComment="")
+GameplayTagList=(Tag="Event.FOV.Increase",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.Hold.Release",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Equip",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Equip.Start",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Combat.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Combat.ChargedAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Combat.LightAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Death",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Equip",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash",DevComment="")
+GameplayTagList=(Tag="State.Death",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Weapon.Spear",DevComment="")
+GameplayTagList=(Tag="Weapon.Sword",DevComment="")

